import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const url = 'http://127.0.0.1:5181';

test('edição de empréstimo: preenchimento, cálculos, cliente, erro, pagamentos e mobile', {timeout:120000}, async t => {
  await import('../../../backend/tests/setup-env.js');
  process.env.FRONTEND_ORIGIN = url;
  const { app } = await import('../../../backend/src/app.js');
  const { openDatabase, closeDatabase, database } = await import('../../../backend/src/config/database.js');
  const { createMaster } = await import('../../../backend/src/modules/auth/auth.service.js');
  const { createClient } = await import('../../../backend/src/modules/clients/clients.service.js');
  const { createLoan, getLoan, updateLoan } = await import('../../../backend/src/modules/loans/loans.service.js');
  const { today, addDays } = await import('../../../backend/src/shared/utils/dates.js');
  let api, vite, browser;
  t.after(async () => {
    await browser?.close(); await vite?.close();
    if (api) { api.closeAllConnections(); await new Promise(resolve => api.close(resolve)); }
    await closeDatabase();
  });
  await openDatabase(':memory:');
  await createMaster({name:'Admin QA',email:'loans@qa.test',cpf:'12345678909',password:'QaSenha123'});
  const actor = await database().prepare('SELECT * FROM users LIMIT 1').get();
  const client = await createClient({companyIds:[1],name:'Cliente Original',cpf:'52998224725'},actor);
  const other = await createClient({companyIds:[2],name:'Cliente Novo',cpf:'11144477735'},actor);
  let loan = await createLoan({company_id:1,client_id:client.id,principal_amount:10000,interest_percentage:'10',installment_count:3,
    installments:[5000,3000,3000],late_fee_per_day:100,loan_date:today(),first_due_date:today()},actor);
  const otherLoan = await createLoan({company_id:2,client_id:other.id,principal_amount:10000,interest_percentage:'0',installment_count:1,
    late_fee_per_day:0,loan_date:today(),first_due_date:today()},actor);
  await updateLoan(otherLoan.id,{revision:otherLoan.revision,status:'cancelled'},actor);
  const originalCompanyLoan = await createLoan({company_id:1,client_id:client.id,principal_amount:10000,interest_percentage:'0',installment_count:1,
    late_fee_per_day:0,loan_date:today(),first_due_date:today()},actor);
  await updateLoan(originalCompanyLoan.id,{revision:originalCompanyLoan.revision,status:'cancelled'},actor);
  api = app.listen(33023,'127.0.0.1');
  await new Promise(resolve => api.once('listening',resolve));
  const { createServer } = await import('vite');
  vite = await createServer({mode:'test',root:fileURLToPath(new URL('../..',import.meta.url)),server:{host:'127.0.0.1',port:5181,strictPort:true,proxy:{'/api':'http://127.0.0.1:33023'}}});
  await vite.listen();
  browser = await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE ? {executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE} : {})});
  const page = await browser.newPage({viewport:{width:1440,height:1000}});
  const errors = [];
  page.on('pageerror',e => errors.push(e.message));
  page.on('console',message => { if (['error','warning'].includes(message.type()) && !/status of (401|409)/.test(message.text())) errors.push(message.text()); });
  const artifacts = process.env.E2E_ARTIFACT_DIR || mkdtempSync(join(tmpdir(),'paytrack-loan-edit-'));
  t.diagnostic('Capturas: '+artifacts);
  await page.goto(url+'/login');
  await page.getByLabel('E-mail',{exact:true}).fill('loans@qa.test');
  await page.locator('#password').fill('QaSenha123');
  await page.getByRole('button',{name:'Entrar',exact:true}).click();
  await page.waitForURL(url+'/');
  await page.goto(url+'/loans');
  const edit = () => page.getByRole('button',{name:/^Abrir parcelas do empréstimo/}).getByRole('button',{name:/^Editar empréstimo de/});
  await edit().click();
  let modal = page.getByRole('dialog');
  await modal.getByRole('heading',{name:'Editar empréstimo'}).waitFor();
  await page.waitForFunction(() => document.querySelector('[placeholder="Digite o nome do cliente"]')?.value === 'Cliente Original');
  await modal.getByLabel('Empresa',{exact:true}).selectOption('2');
  assert.equal(await modal.getByLabel('Empresa',{exact:true}).isEnabled(),true);
  assert.equal(await modal.getByPlaceholder('Digite o nome do cliente').inputValue(),'');
  const filtered = page.waitForResponse(r => r.url().includes('/clients?') && r.url().includes('company_id=2') && r.url().includes('search=Cliente'));
  await modal.getByPlaceholder('Digite o nome do cliente').fill('Cliente');
  await filtered;
  await modal.getByRole('button',{name:/Cliente Novo/}).waitFor();
  assert.equal(await modal.getByRole('button',{name:/Cliente Original/}).count(),0);
  assert.equal(await modal.getByLabel('Valor emprestado').inputValue(),'100.00');
  assert.equal(await modal.getByLabel('Parcela 1').inputValue(),'50.00');
  assert.equal(await modal.getByLabel('Parcela 2').inputValue(),'30.00');
  await page.screenshot({path:join(artifacts,'loan-edit-desktop.png'),animations:'disabled'});
  await modal.getByLabel('Valor emprestado').fill('200');
  await modal.getByLabel(/Juros/).fill('20');
  await modal.getByLabel('Quantidade de parcelas').fill('4');
  await modal.getByLabel('Multa por dia de atraso').fill('2.50');
  await modal.getByLabel('Data do empréstimo').fill(addDays(today(),-1));
  await modal.getByLabel('Início do pagamento').fill(addDays(today(),1));
  await modal.getByLabel('Parcela 1').fill('90');
  await modal.getByLabel('Parcela 2').click();
  assert.equal(await modal.getByLabel('Parcela 2').inputValue(),'50.00');
  await modal.getByPlaceholder('Digite o nome do cliente').fill('Cliente Novo');
  await modal.getByRole('button',{name:/Cliente Novo/}).click();
  const save = page.waitForResponse(r => r.url().endsWith('/loans/'+loan.id) && r.request().method()==='PATCH');
  await modal.getByRole('button',{name:'Salvar alterações'}).click();
  assert.equal((await save).status(),200);
  await modal.waitFor({state:'hidden'});
  loan = await getLoan(loan.id);
  assert.equal(loan.client_id,other.id); assert.equal(loan.total_amount,24000);
  assert.equal(loan.company_id,2);
  assert.equal(loan.loan_date,addDays(today(),-1));
  assert.equal(loan.first_due_date,addDays(today(),1));
  assert.deepEqual(loan.installments.map(i=>i.amount),[9000,5000,5000,5000]);
  assert.equal(loan.late_fee_per_day,250);
  // Opening through details uses the same form; cancel does not persist changes.
  await page.getByRole('button',{name:'Abrir parcelas do empréstimo de Cliente Novo'}).click();
  modal = page.getByRole('dialog');
  await modal.getByRole('button',{name:'Editar empréstimo de Cliente Novo'}).click();
  modal = page.getByRole('dialog').filter({has:page.getByRole('heading',{name:'Editar empréstimo',exact:true})});
  await modal.getByRole('heading',{name:'Editar empréstimo'}).waitFor();
  assert.equal(await modal.getByLabel('Parcela 1').inputValue(),'90.00');
  await modal.getByLabel('Valor emprestado').fill('300');
  await modal.getByRole('button',{name:'Cancelar',exact:true}).click();
  await modal.waitFor({state:'hidden'});
  assert.equal((await getLoan(loan.id)).principal_amount,20000);
  // A concurrent update leaves the form and draft open with the server error.
  await edit().click();
  await modal.getByRole('heading',{name:'Editar empréstimo'}).waitFor();
  loan = await updateLoan(loan.id,{revision:loan.revision,notes:'Outra tela'},actor);
  await modal.getByLabel('Valor emprestado').fill('250');
  await modal.getByRole('button',{name:'Salvar alterações'}).click();
  await page.getByText('Este contrato foi alterado. Reabra-o antes de salvar novamente.',{exact:true}).waitFor();
  assert.equal(await modal.getByLabel('Valor emprestado').inputValue(),'250');
  await modal.getByRole('button',{name:'Cancelar',exact:true}).click();
  await modal.waitFor({state:'hidden'});
  await page.getByRole('alert').getByRole('button',{name:'Fechar notificação'}).click();
  await page.getByRole('alert').waitFor({state:'hidden'});
  // Partial receipts allow compatible changes on mobile without losing history.
  await database().prepare('INSERT INTO payments(installment_id,amount,payment_date,created_by) VALUES(?,?,?,?)')
    .run(loan.installments[0].id,1000,today(),actor.id);
  await page.setViewportSize({width:390,height:844});
  await edit().click();
  await modal.getByRole('heading',{name:'Editar empréstimo'}).waitFor();
  assert.equal(await modal.getByLabel('Valor emprestado').isEnabled(),true);
  assert.equal(await modal.getByLabel('Parcela 1').isEnabled(),true);
  assert.equal(await modal.getByPlaceholder('Digite o nome do cliente').isEnabled(),true);
  assert.ok(await modal.evaluate(node => node.scrollWidth <= window.innerWidth));
  await page.screenshot({path:join(artifacts,'loan-edit-mobile.png'),animations:'disabled'});
  await modal.getByLabel('Empresa',{exact:true}).selectOption('1');
  await modal.getByLabel('Valor emprestado').fill('300');
  await modal.getByLabel('Parcela 1').fill('120');
  await modal.getByPlaceholder('Digite o nome do cliente').fill('Cliente Original');
  await modal.getByRole('button',{name:/Cliente Original/}).click();
  await modal.getByRole('button',{name:'Salvar alterações'}).click();
  await modal.waitFor({state:'hidden'});
  loan = await getLoan(loan.id);
  assert.equal(loan.client_id,client.id); assert.equal(loan.paid_amount,1000);
  assert.equal(loan.company_id,1);
  assert.equal(loan.payments.length,1);
  assert.deepEqual(loan.installments.map(i=>i.amount),[12000,8000,8000,8000]);
  // The shared form still creates a fresh contract after editing.
  await page.getByRole('button',{name:'Novo empréstimo',exact:true}).click();
  modal = page.getByRole('dialog').filter({has:page.getByRole('heading',{name:'Novo empréstimo',exact:true})});
  await modal.getByLabel('Empresa',{exact:true}).selectOption('2');
  assert.equal(await modal.getByLabel('Valor emprestado').inputValue(),'');
  await modal.getByPlaceholder('Digite o nome do cliente').fill('Cliente Novo');
  await modal.getByRole('button',{name:/Cliente Novo/}).click();
  await modal.getByLabel('Valor emprestado').fill('100');
  await modal.getByLabel(/Juros/).fill('10');
  await modal.getByLabel('Multa por dia de atraso').fill('0');
  await modal.getByLabel('Data do empréstimo').fill(today());
  await modal.getByLabel('Início do pagamento').fill(today());
  const created = page.waitForResponse(r=>r.url().endsWith('/loans') && r.request().method()==='POST');
  await modal.getByRole('button',{name:'Criar empréstimo',exact:true}).click();
  assert.equal((await created).status(),201);
  await modal.waitFor({state:'hidden'});
  assert.equal((await database().prepare('SELECT count(*) n FROM loans').get()).n,4);
  assert.equal(page.url(),url+'/loans'); assert.match(await page.title(),/PayTrack/i);
  assert.ok((await page.locator('body').innerText()).length>100);
  assert.equal(await page.locator('vite-error-overlay').count(),0);
  assert.deepEqual(errors,[]);

  // A regular member can edit permitted loans but cannot change their company.
  const { insertUser } = await import('../../../backend/src/modules/auth/auth.repository.js');
  const { setMembership } = await import('../../../backend/src/modules/companies/companies.repository.js');
  const member = await insertUser({name:'Membro QA',email:'member-loans@qa.test',cpf:null,passwordHash:actor.password_hash},'user','active');
  await setMembership(member,1,'USER');
  const memberPage = await browser.newPage({viewport:{width:1440,height:1000}});
  memberPage.on('pageerror',e => errors.push(e.message));
  await memberPage.goto(url+'/login');
  await memberPage.getByLabel('E-mail',{exact:true}).fill('member-loans@qa.test');
  await memberPage.locator('#password').fill('QaSenha123');
  await memberPage.getByRole('button',{name:'Entrar',exact:true}).click();
  await memberPage.waitForURL(url+'/');
  await memberPage.goto(url+'/loans');
  await memberPage.getByRole('button',{name:'Editar empréstimo de Cliente Original',exact:true}).click();
  const memberModal = memberPage.getByRole('dialog');
  await memberModal.getByRole('heading',{name:'Editar empréstimo'}).waitFor();
  assert.equal(await memberModal.getByLabel('Empresa',{exact:true}).count(),0);
  assert.equal(await memberModal.getByLabel('Valor emprestado').isEnabled(),true);
  await memberModal.getByLabel(/Juros/).fill('25');
  const memberSave = memberPage.waitForResponse(r => r.url().endsWith('/loans/'+loan.id) && r.request().method()==='PATCH');
  await memberModal.getByRole('button',{name:'Salvar alterações'}).click();
  assert.equal((await memberSave).status(),200);
  await memberModal.waitFor({state:'hidden'});
  const memberResult = await getLoan(loan.id);
  assert.equal(memberResult.company_id,1);
  assert.equal(Number(memberResult.interest_percentage),25);
  assert.equal(memberResult.paid_amount,1000);
  assert.deepEqual(errors,[]);
});
