CREATE FUNCTION ascii_lower(value TEXT) RETURNS TEXT LANGUAGE SQL IMMUTABLE STRICT AS $$
  SELECT translate(value, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz')
$$;
-- Preserve ISO text dates/timestamps exposed by the existing API.
CREATE FUNCTION utc_now() RETURNS TEXT LANGUAGE SQL VOLATILE AS $$
  SELECT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
$$;
CREATE FUNCTION day_number(value TEXT) RETURNS INTEGER LANGUAGE SQL IMMUTABLE STRICT AS $$
  SELECT value::date - DATE '1970-01-01'
$$;
CREATE FUNCTION money_share(amount NUMERIC, numerator NUMERIC, denominator NUMERIC)
RETURNS NUMERIC LANGUAGE SQL IMMUTABLE STRICT AS $$
  SELECT trunc((amount*numerator+trunc(denominator/2))/denominator)
$$;
CREATE FUNCTION can_access_company(company BIGINT) RETURNS BOOLEAN LANGUAGE SQL STABLE AS $$
  SELECT COALESCE(current_setting('paytrack.access',true)::jsonb->>'role'='admin'
    OR (current_setting('paytrack.access',true)::jsonb->'companyIds') @> to_jsonb(company),false)
$$;


CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    cpf TEXT UNIQUE,
    rg TEXT UNIQUE,
    cnh TEXT UNIQUE,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'user' CHECK(role IN ('admin', 'user')),
    access_status TEXT NOT NULL DEFAULT 'pending' CHECK(access_status IN ('pending','active','rejected','blocked')),
    approved_by BIGINT REFERENCES users(id),
    approved_at TEXT,
    rejected_at TEXT,
    blocked_at TEXT,
    password_changed_at TEXT,
    last_login_at TEXT,
    created_at TEXT NOT NULL DEFAULT utc_now(),
    updated_at TEXT NOT NULL DEFAULT utc_now()
);

CREATE TABLE IF NOT EXISTS auth_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    token_hash TEXT NOT NULL UNIQUE,
    csrf_token TEXT NOT NULL,
    created_at BIGINT NOT NULL,
    expires_at BIGINT NOT NULL,
    last_seen_at BIGINT NOT NULL,
    revoked_at BIGINT
);
CREATE INDEX IF NOT EXISTS idx_auth_sessions_user ON auth_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_auth_sessions_expiry ON auth_sessions(expires_at);
CREATE TABLE IF NOT EXISTS auth_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event TEXT NOT NULL,
    actor_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    subject_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    actor_name TEXT,
    entity_type TEXT,
    entity_id BIGINT,
    details TEXT CHECK(details IS NULL OR details::jsonb IS NOT NULL),
    created_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_auth_audit_entity ON auth_audit_logs(entity_type,entity_id,id);
CREATE TABLE IF NOT EXISTS auth_rate_limits (
    key TEXT PRIMARY KEY,
    hits BIGINT NOT NULL,
    reset_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_auth_rate_expiry ON auth_rate_limits(reset_at);
CREATE INDEX IF NOT EXISTS idx_users_access ON users(access_status);
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email_normalized ON users(ascii_lower(trim(email)));





CREATE TABLE IF NOT EXISTS companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE CHECK(length(trim(name)) BETWEEN 2 AND 150),
    created_at TEXT NOT NULL DEFAULT utc_now()
);
CREATE TABLE IF NOT EXISTS user_companies (
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
    PRIMARY KEY(user_id,company_id)
);
CREATE INDEX IF NOT EXISTS idx_user_companies_company ON user_companies(company_id,user_id);

CREATE TABLE IF NOT EXISTS clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
    name TEXT NOT NULL,
    cpf TEXT NOT NULL,
    rg TEXT,
    cnh TEXT,
    phone TEXT,
    email TEXT,
    status TEXT NOT NULL DEFAULT 'sem_contrato'
        CHECK (status IN ('sem_contrato', 'ativo', 'quitado', 'negativado')),
    notes TEXT,
    created_by BIGINT,
    status_override TEXT CHECK (status_override IS NULL OR status_override = 'negativado'),
    created_at TEXT NOT NULL DEFAULT utc_now(),
    updated_at TEXT NOT NULL DEFAULT utc_now(),
    UNIQUE(company_id,cpf),
    UNIQUE(company_id,rg),
    UNIQUE(company_id,cnh),
    FOREIGN KEY (created_by) REFERENCES users(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS loans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL,
    principal_amount BIGINT NOT NULL CHECK (principal_amount > 0),
    interest_percentage NUMERIC NOT NULL DEFAULT 0 CHECK (interest_percentage >= 0),
    interest_amount BIGINT NOT NULL DEFAULT 0 CHECK (interest_amount >= 0),
    total_amount BIGINT NOT NULL CHECK (total_amount > 0),
    installment_count BIGINT NOT NULL CHECK (installment_count > 0),
    late_fee_per_day BIGINT NOT NULL DEFAULT 0 CHECK (late_fee_per_day >= 0),
    loan_date TEXT NOT NULL,
    first_due_date TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'paid', 'overdue', 'cancelled')),
    notes TEXT,
    created_by BIGINT,
    revision BIGINT NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT utc_now(),
    updated_at TEXT NOT NULL DEFAULT utc_now(),
    FOREIGN KEY (client_id) REFERENCES clients(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    FOREIGN KEY (created_by) REFERENCES users(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS installments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_id BIGINT NOT NULL,
    installment_number BIGINT NOT NULL CHECK (installment_number > 0),
    amount BIGINT NOT NULL CHECK (amount > 0),
    due_date TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'paid', 'overdue', 'partial')),
    paid_amount BIGINT NOT NULL DEFAULT 0 CHECK (paid_amount >= 0),
    paid_at TEXT,
    created_at TEXT NOT NULL DEFAULT utc_now(),
    updated_at TEXT NOT NULL DEFAULT utc_now(),
    UNIQUE (loan_id, installment_number),
    FOREIGN KEY (loan_id) REFERENCES loans(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    installment_id BIGINT NOT NULL,
    amount BIGINT NOT NULL CHECK (amount >= 0),
    late_fee_amount BIGINT NOT NULL DEFAULT 0 CHECK (late_fee_amount >= 0),
    payment_date TEXT NOT NULL,
    payment_method TEXT,
    notes TEXT,
    created_by BIGINT,
    created_at TEXT NOT NULL DEFAULT utc_now(),
    voided_at TEXT,
    CHECK (amount > 0 OR late_fee_amount > 0),
    FOREIGN KEY (installment_id) REFERENCES installments(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    FOREIGN KEY (created_by) REFERENCES users(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS late_fees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    installment_id BIGINT NOT NULL UNIQUE,
    days_late BIGINT NOT NULL DEFAULT 0 CHECK (days_late >= 0),
    amount BIGINT NOT NULL DEFAULT 0 CHECK (amount >= 0),
    paid_amount BIGINT NOT NULL DEFAULT 0 CHECK (paid_amount >= 0),
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'partial', 'paid', 'waived')),
    paid_at TEXT,
    created_at TEXT NOT NULL DEFAULT utc_now(),
    updated_at TEXT NOT NULL DEFAULT utc_now(),
    FOREIGN KEY (installment_id) REFERENCES installments(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_clients_status
    ON clients(status);

CREATE INDEX IF NOT EXISTS idx_loans_client_id
    ON loans(client_id);

CREATE INDEX IF NOT EXISTS idx_loans_status
    ON loans(status);

CREATE INDEX IF NOT EXISTS idx_installments_loan_id
    ON installments(loan_id);

CREATE INDEX IF NOT EXISTS idx_installments_status
    ON installments(status);

CREATE INDEX IF NOT EXISTS idx_installments_due_date
    ON installments(due_date);

CREATE INDEX IF NOT EXISTS idx_payments_installment_id
    ON payments(installment_id);

CREATE INDEX IF NOT EXISTS idx_payments_payment_date
    ON payments(payment_date);

CREATE INDEX IF NOT EXISTS idx_late_fees_status
    ON late_fees(status);




CREATE INDEX IF NOT EXISTS idx_users_approved_by ON users(approved_by);
CREATE INDEX IF NOT EXISTS idx_auth_audit_actor ON auth_audit_logs(actor_id);
CREATE INDEX IF NOT EXISTS idx_auth_audit_subject ON auth_audit_logs(subject_id);
CREATE INDEX IF NOT EXISTS idx_clients_created_by ON clients(created_by);
CREATE INDEX IF NOT EXISTS idx_loans_created_by ON loans(created_by);
CREATE INDEX IF NOT EXISTS idx_payments_created_by ON payments(created_by);

CREATE UNIQUE INDEX idx_companies_name_normalized ON companies(ascii_lower(name));
INSERT INTO companies(id,name) VALUES (1,'Dinheiro Express'),(2,'Platinum Finance');
SELECT setval(pg_get_serial_sequence('companies','id'),2,true);
CREATE VIEW scoped_clients AS SELECT * FROM clients WHERE can_access_company(company_id);
    CREATE VIEW scoped_loans AS SELECT l.*,c.company_id FROM loans l JOIN scoped_clients c ON c.id=l.client_id;
    CREATE VIEW scoped_installments AS SELECT i.* FROM installments i JOIN scoped_loans l ON l.id=i.loan_id;
    CREATE VIEW scoped_payments AS SELECT p.* FROM payments p JOIN scoped_installments i ON i.id=p.installment_id;
    CREATE VIEW scoped_late_fees AS SELECT f.* FROM late_fees f JOIN scoped_installments i ON i.id=f.installment_id;
    CREATE VIEW scoped_auth_audit_logs AS SELECT a.* FROM auth_audit_logs a WHERE
      (a.entity_type='client' AND a.entity_id IN (SELECT id FROM scoped_clients)) OR
      (a.entity_type='loan' AND a.entity_id IN (SELECT id FROM scoped_loans)) OR
      (a.entity_type='payment' AND a.entity_id IN (SELECT id FROM scoped_payments));
CREATE FUNCTION preserve_last_admin() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF OLD.role='admin' AND OLD.access_status='active' THEN
    IF TG_OP='DELETE' OR NEW.role<>'admin' OR NEW.access_status<>'active' THEN
      IF (SELECT count(*) FROM users WHERE role='admin' AND access_status='active')<=1 THEN
        RAISE EXCEPTION 'Last active administrator' USING ERRCODE='23514';
      END IF;
    END IF;
  END IF;
  IF TG_OP='DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END $$;
CREATE FUNCTION lock_admin_changes() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  PERFORM pg_advisory_xact_lock(728194001);
  RETURN NULL;
END $$;
CREATE TRIGGER lock_admin_changes BEFORE INSERT OR UPDATE OR DELETE ON users
FOR EACH STATEMENT EXECUTE FUNCTION lock_admin_changes();
CREATE TRIGGER protect_last_admin_update BEFORE UPDATE OF role,access_status ON users
FOR EACH ROW EXECUTE FUNCTION preserve_last_admin();
CREATE TRIGGER protect_last_admin_delete BEFORE DELETE ON users
FOR EACH ROW EXECUTE FUNCTION preserve_last_admin();
CREATE FUNCTION preserve_financial_owner() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF to_jsonb(NEW)->TG_ARGV[0] IS DISTINCT FROM to_jsonb(OLD)->TG_ARGV[0] THEN
    RAISE EXCEPTION 'Financial owner is immutable' USING ERRCODE='23514';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER clients_company_immutable BEFORE UPDATE OF company_id ON clients
FOR EACH ROW EXECUTE FUNCTION preserve_financial_owner('company_id');
CREATE TRIGGER loans_client_immutable BEFORE UPDATE OF client_id ON loans
FOR EACH ROW EXECUTE FUNCTION preserve_financial_owner('client_id');

CREATE FUNCTION guard_clients() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP<>'INSERT' AND NOT (can_access_company(OLD.company_id)) THEN
    RAISE EXCEPTION 'Company access denied' USING ERRCODE='23514';
  END IF;
  IF TG_OP<>'DELETE' AND NOT (can_access_company(NEW.company_id)) THEN
    RAISE EXCEPTION 'Company access denied' USING ERRCODE='23514';
  END IF;
  IF TG_OP='DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER guard_clients BEFORE INSERT OR UPDATE OR DELETE ON clients
FOR EACH ROW EXECUTE FUNCTION guard_clients();

CREATE FUNCTION guard_loans() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP<>'INSERT' AND NOT (EXISTS(SELECT 1 FROM scoped_clients WHERE id=OLD.client_id)) THEN
    RAISE EXCEPTION 'Company access denied' USING ERRCODE='23514';
  END IF;
  IF TG_OP<>'DELETE' AND NOT (EXISTS(SELECT 1 FROM scoped_clients WHERE id=NEW.client_id)) THEN
    RAISE EXCEPTION 'Company access denied' USING ERRCODE='23514';
  END IF;
  IF TG_OP='DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER guard_loans BEFORE INSERT OR UPDATE OR DELETE ON loans
FOR EACH ROW EXECUTE FUNCTION guard_loans();

CREATE FUNCTION guard_installments() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP<>'INSERT' AND NOT (EXISTS(SELECT 1 FROM scoped_loans WHERE id=OLD.loan_id)) THEN
    RAISE EXCEPTION 'Company access denied' USING ERRCODE='23514';
  END IF;
  IF TG_OP<>'DELETE' AND NOT (EXISTS(SELECT 1 FROM scoped_loans WHERE id=NEW.loan_id)) THEN
    RAISE EXCEPTION 'Company access denied' USING ERRCODE='23514';
  END IF;
  IF TG_OP='DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER guard_installments BEFORE INSERT OR UPDATE OR DELETE ON installments
FOR EACH ROW EXECUTE FUNCTION guard_installments();

CREATE FUNCTION guard_payments() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP<>'INSERT' AND NOT (EXISTS(SELECT 1 FROM scoped_installments WHERE id=OLD.installment_id)) THEN
    RAISE EXCEPTION 'Company access denied' USING ERRCODE='23514';
  END IF;
  IF TG_OP<>'DELETE' AND NOT (EXISTS(SELECT 1 FROM scoped_installments WHERE id=NEW.installment_id)) THEN
    RAISE EXCEPTION 'Company access denied' USING ERRCODE='23514';
  END IF;
  IF TG_OP='DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER guard_payments BEFORE INSERT OR UPDATE OR DELETE ON payments
FOR EACH ROW EXECUTE FUNCTION guard_payments();

CREATE FUNCTION guard_late_fees() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP<>'INSERT' AND NOT (EXISTS(SELECT 1 FROM scoped_installments WHERE id=OLD.installment_id)) THEN
    RAISE EXCEPTION 'Company access denied' USING ERRCODE='23514';
  END IF;
  IF TG_OP<>'DELETE' AND NOT (EXISTS(SELECT 1 FROM scoped_installments WHERE id=NEW.installment_id)) THEN
    RAISE EXCEPTION 'Company access denied' USING ERRCODE='23514';
  END IF;
  IF TG_OP='DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER guard_late_fees BEFORE INSERT OR UPDATE OR DELETE ON late_fees
FOR EACH ROW EXECUTE FUNCTION guard_late_fees();
